from board import SW_LEFT, SW_RIGHT, SW_UP, SW_DOWN, SW_A, SW_B, SW_X, SW_Y

# CONTROLLER_START = <pin>
# CONTROLLER_SELECT = <pin>
CONTROLLER_LEFT = SW_LEFT
CONTROLLER_RIGHT = SW_RIGHT
CONTROLLER_UP = SW_UP
CONTROLLER_DOWN = SW_DOWN
CONTROLLER_A = SW_A
CONTROLLER_B = SW_B
CONTROLLER_X = SW_X
CONTROLLER_Y = SW_Y
# CONTROLLER_LS = <pin>
# CONTROLLER_RS = <pin>
