from board import SW_LEFT, SW_RIGHT, SW_UP, SW_DOWN, SW_A, SW_B, SW_X, SW_Y

# BUTTON_START = <pin>
# BUTTON_SELECT = <pin>
BUTTON_LEFT = SW_LEFT
BUTTON_RIGHT = SW_RIGHT
BUTTON_UP = SW_UP
BUTTON_DOWN = SW_DOWN
BUTTON_A = SW_A
BUTTON_B = SW_B
BUTTON_X = SW_X
BUTTON_Y = SW_Y
# BUTTON_LS = <pin>
# BUTTON_RS = <pin>
